### ISSUE TITLE
Bot no longer posts instructions on failed backports

### ISSUE THREAD

**Issue by pllim** [MeeseeksBox/MeeseeksDev#92]
Desired: Detailed manual backport instructions as before.

What it is currently saying, "Oops, something went wrong applying the patch ... Please have a look at my logs." However, users cannot access server logs.

Example occurrences:

* https://github.com/astropy/astropy/pull/13991#issuecomment-1305920111
* https://github.com/spacetelescope/jdaviz/pull/1836#issuecomment-1313975699

**Comment by blink1073** [comment]
Hi @pllim, I think this should be resolved by #91.  Please let us know if you see the issue again.

**Comment by pllim** [comment]
Thanks for the update! I'll report back next time I invoke the bot again. 🙇‍♀️

**Comment by pllim** [comment]
Hmm... It is still not showing for me, see https://github.com/spacetelescope/jdaviz/pull/1836#issuecomment-1329796921

**Comment by blink1073** [comment]
Ah, I had not successfully deployed #91, done now.

**Comment by pllim** [comment]
Yay, it works again. Thank you so much!!!

https://github.com/spacetelescope/jdaviz/pull/1836#issuecomment-1329942658

**Comment by blink1073** [comment]
Woohoo, thanks for confirming!
